# Generated by Django 6.0.1 on 2026-03-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('football', 'ฟุตบอล'), ('futsal', 'ฟุตซอล'), ('football7', 'หญ้าเทียม')], max_length=20),
        ),
    ]
