# Generated by Django 6.0.1 on 2026-03-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
