# Generated by Django 6.0.1 on 2026-03-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_field_is_active_alter_booking_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='water_packs',
            field=models.IntegerField(default=0),
        ),
    ]
