# Generated by Django 6.0.1 on 2026-03-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_balls_booking_water_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_walkin',
            field=models.BooleanField(default=False),
        ),
    ]
